{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /health
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: {{ .Values.proxyService.service.port }}
        - path: /api/users
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: {{ .Values.proxyService.service.port }}         
        - path: /api/movies
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: {{ .Values.proxyService.service.port }}
        - path: /api/movies/health
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: {{ .Values.proxyService.service.port }}
        - path: /api/payments
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: {{ .Values.proxyService.service.port }}                
        - path: /api/subscriptions
          pathType: Prefix
          backend:
            service:
              name: proxy-service
              port:
                number: {{ .Values.proxyService.service.port }}    
        - path: /api/events
          pathType: Prefix
          backend:
            service:
              name: events-service
              port:
                number: {{ .Values.eventsService.service.port }}
{{- end }}