apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgICAgICAgImdoY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiZG05NWRHVnVhMjkyUUdsdVltOTRMbkoxT21kb2NGOTFkMGxyYUV4TFQwTjRSVVZ4YkVGc1JFMWlOR1U1VVhSME9VcEhXbEV6YTFrM1RVST0iCiAgICAgICAgICAgICAgICB9Cgl9LAoJImN1cnJlbnRDb250ZXh0IjogImNvbGltYSIKfQo=
type: kubernetes.io/dockerconfigjson
