apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: cinemaabyss
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: cinemaabyss.example.com
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000            
          - path: /api/movies
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000                        
          - path: /api/subscriptions
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000             
          - path: /api/events
            pathType: Prefix
            backend:
              service:
                name: events-service
                port:
                  number: 8000
