# Global settings
global:
  namespace: cinemaabyss
  domain: cinemaabyss.example.com

# Image pull secrets
imagePullSecrets:
  dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgICAgICAgImdoY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiZG05NWRHVnVhMjkyUUdsdVltOTRMbkoxT21kb2NGOTFkMGxyYUV4TFQwTjRSVVZ4YkVGc1JFMWlOR1U1VVhSME9VcEhXbEV6YTFrM1RVST0iCiAgICAgICAgICAgICAgICB9Cgl9LAoJImN1cnJlbnRDb250ZXh0IjogImNvbGltYSIKfQo=
# Database configuration
database:
  host: postgres
  port: 5432
  name: cinemaabyss
  user: postgres
  password: cG9zdGdyZXNfcGFzc3dvcmQ=
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 50Mi
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

# Monolith configuration
monolith:
  enabled: true
  image:
    repository: ghcr.io/voitenkov-courses/architecture-pro-cinemaabyss/monolith
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 10Mi
  service:
    port: 8080
    targetPort: 8080
    type: ClusterIP

# Proxy service configuration
proxyService:
  enabled: true
  image:
    repository: ghcr.io/voitenkov-courses/architecture-pro-cinemaabyss/proxy-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 10Mi
  service:
    port: 80
    targetPort: 8000
    type: ClusterIP

# Movies service configuration
moviesService:
  enabled: true
  image:
    repository: ghcr.io/voitenkov-courses/architecture-pro-cinemaabyss/movies-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 10Mi
  service:
    port: 8081
    targetPort: 8081
    type: ClusterIP

# Events service configuration
eventsService:
  enabled: true
  image:
    repository: ghcr.io/voitenkov-courses/architecture-pro-cinemaabyss/events-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 10Mi
  service:
    port: 8082
    targetPort: 8082
    type: ClusterIP
  kafkaBrokers: "kafka:9092"

# Kafka configuration
kafka:
  enabled: true
  image:
    repository: apache/kafka
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 50Mi
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  host: cinemaabyss.example.com

# Application configuration
config:
  # Strangler Fig configuration
  gradualMigration: "true"
  moviesMigrationPercent: "100"
